version: "1.0.0"
env: "dev"
server:
  host: "0.0.0.0"
  port: 8016
linuxUser: "root"
poolNum: 100
log:
  dir: "/tmp/logs"
  name: "jumpserver.log"
  format: ""
  retainDay: 3
  Level: "INFO"

mysql:
  host: "127.0.0.1"
  port: 3306
  db: "sso"
  user: "root"
  password: "123456"
  charset: "utf8"

redis:
  host: "127.0.0.1"
  port: 6379
  poolSize: 3
  maxRetries: 3
